spring:
  profiles:
    active: dev
  datasource:
    platform: h2
    url: jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  datasource.username: sa
  datasource.password:

  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true

  h2:
    console:
      enabled: true
  
logging:
  level:
    #org.springframework.beans: debug
    fr.cheville.escalade.bloc: DEBUG
    org.hibernate.SQL: DEBUG
